name: Porter augmentos-cloud-staging

on:
  push:
    branches:
      - porter

jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git SHA tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Porter CLI
        uses: porter-dev/setup-porter@v0.1.0

      - name: Deploy stack to Staging
        timeout-minutes: 30
        run: exec porter apply -n $PORTER_NAMESPACE -f ./augmentos_cloud/porter.yaml
        env:
          PORTER_APP_NAME: augmentos-cloud-staging
          PORTER_NAMESPACE: staging
          NODE_ENV: staging
          PORTER_CLUSTER: "4689"         # If using the same cluster, or update as needed
          PORTER_PROJECT: "15081"
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4689 }}
